//
// Generated by JTB 1.2.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All Object visitors must implement this interface.
 */
public interface ObjectVisitor {
   //
   // Object Auto class visitors
   //
   public Object visit(NodeList n, Object argu);
   public Object visit(NodeListOptional n, Object argu);
   public Object visit(NodeOptional n, Object argu);
   public Object visit(NodeSequence n, Object argu);
   public Object visit(NodeToken n, Object argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expression()
    * f1 -> ";"
    */
   public Object visit(Start n, Object argu);

   /**
    * f0 -> AdditiveExpression()
    */
   public Object visit(Expression n, Object argu);

   /**
    * f0 -> MultiplicativeExpression()
    * f1 -> ( ( "+" | "-" ) MultiplicativeExpression() )*
    */
   public Object visit(AdditiveExpression n, Object argu);

   /**
    * f0 -> UnaryExpression()
    * f1 -> ( ( "*" | "/" | "%" ) UnaryExpression() )*
    */
   public Object visit(MultiplicativeExpression n, Object argu);

   /**
    * f0 -> "(" Expression() ")"
    *       | Identifier()
    *       | MyInteger()
    */
   public Object visit(UnaryExpression n, Object argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public Object visit(Identifier n, Object argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public Object visit(MyInteger n, Object argu);

}
