package javacc_generated;

/* Generated By:JavaCC: Do not edit this line. ArithExprConstants.java */
public interface ArithExprConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 7;
  int DECIMAL_LITERAL = 8;
  int HEX_LITERAL = 9;
  int OCTAL_LITERAL = 10;
  int IDENTIFIER = 11;
  int LETTER = 12;
  int DIGIT = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
  };

}
